### ISSUE TITLE
[Feature request] Avatar replacement

### ISSUE THREAD

**Issue by kwadroke** [jayber/wevr#1]
I'm looking to use wevr for my project and I would like to replace the avatar for players. 

Is it currently possible to override the default avatar? If not, can the parent a-sphere be changed to an a-entity without a primitive and with the current a-sphere as a child so that the avatar HTML can be replaced with innerHTML or the like?

Basically what I'm wanting to do is use a gltf model for the player avatar instead of the current one.

**Comment by jayber** [comment]
I'm glad you're thinking of using wevr!

That sounds like a very useful feature. I'll look to add it ASAP. Possibly as an event emitted when the connection is successful.

Also, just so that you're aware, wevr is very new and very much in development, so there may be a few bumps in the road as dev continues. Please let me know of any issues and bugs :-)

**Comment by kwadroke** [comment]
Thanks.

**Comment by jayber** [comment]
Hi 

I've added avatar templating to wevr:
https://github.com/jayber/wevr#avatar-overriding

Take a look and let me know if you have any problems or suggestions.
